# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 84e737221af637240b0763027e36cb85b56c9e677594286d4090ca75b7bfb51837fbc3163dac598e45e813bb679b29198896c391255bb7efc718b5ba30dfd983

test:
  secret_key_base: af83055c5d29e7904fc98cc56bc1f2a73345fddb7ba55ea17bfd90d654f287638a77b1a380b50fe5843fe58c38d3773f3bc9835dc50ceda84375293e6de5f435

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
